title: "BloomerLab"
description: "게임 개발 취준생의 블로그"
author: "Song mingyu"
email: "smg927@daum.net"
github_username: "smg-927"
twitter_username: ""

url: "https://smg-927.github.io"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
theme: null
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Permalinks
permalink: /:year/:month/:day/:title/

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Collections
collections:
  posts:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Your Name"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: true
